-- Recreate raw_market_snapshots as a RANGE(captured_at) partitioned table, managed by pg_partman.
ALTER TABLE raw_market_snapshots RENAME TO raw_market_snapshots_pre_partition;

-- Index names are independent of the table name, so the renamed table still holds the
-- original index names from 001. Move them aside so the new table can reclaim the canonical
-- names; they are dropped with the pre_partition table at the end of this migration.
ALTER INDEX ix_raw_snap_source_time RENAME TO ix_raw_snap_source_time_old;
ALTER INDEX ix_raw_snap_source_key  RENAME TO ix_raw_snap_source_key_old;
ALTER INDEX raw_market_snapshots_pkey RENAME TO raw_market_snapshots_pkey_old;

CREATE TABLE raw_market_snapshots (
  id           bigint GENERATED BY DEFAULT AS IDENTITY,
  source       text        NOT NULL,
  source_key   text        NOT NULL,
  record_type  text        NOT NULL,
  captured_at  timestamptz NOT NULL,
  payload      jsonb       NOT NULL,
  ingested_at  timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id, captured_at)
) PARTITION BY RANGE (captured_at);

CREATE INDEX ix_raw_snap_source_time ON raw_market_snapshots (source, captured_at);
CREATE INDEX ix_raw_snap_source_key  ON raw_market_snapshots (source, source_key, captured_at);
CREATE INDEX brin_raw_snap_captured  ON raw_market_snapshots USING brin (captured_at);

SELECT partman.create_parent(
  p_parent_table := 'public.raw_market_snapshots',
  p_control      := 'captured_at',
  p_interval     := '1 day',
  p_type         := 'range',
  p_premake      := 4
);

UPDATE partman.part_config
SET retention = '90 days', retention_keep_table = false
WHERE parent_table = 'public.raw_market_snapshots';

-- Copy existing rows (new ids regenerate; raw is a firehose with no inbound FKs).
INSERT INTO raw_market_snapshots (source, source_key, record_type, captured_at, payload, ingested_at)
SELECT source, source_key, record_type, captured_at, payload, ingested_at
FROM raw_market_snapshots_pre_partition;

DROP TABLE raw_market_snapshots_pre_partition;
